version: '3'

services:
  nest:
    container_name: nest_app
    build:
      context: ./
    restart: always
    ports:
      - 3000:3000
    environment:
      - URI_MONGODB=mongodb://db/ticketsbd
      - PORT=3000
      - JWT_SECRET=AEIUIJALKJLAKJLKSX!
    depends_on:
      - db
    links:
      - db



  db: 
    image: mongo:5
    container_name: nest_mongo
    restart: always
    ports:
      - 27018:27017
    environment:
      MONGO_DATABASE: ticketsbd
    volumes:
      - ./mongo:/data/db

  